---
- hosts: jenkins-master
  become: true
  tasks:
  - name: add jenkins key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      state: present

  - name: add jenkins repo
    apt_repository:
      repo: 'deb https://pkg.jenkins.io/debian binary/'
      state: present

  - name: install java
    apt: 
      name: openjdk-11-jre
      state: present

  - name: install jenkins
    apt: 
      name: jenkins
      state: present

  - name: start jenkins service
    service: 
      name: jenkins
      state: started

  - name: enable jenkins to start at boot time
    service:
      name: jenkins
      enabled: yes

  - name: install docker
    apt: 
      name: docker.io
      state: present

  - name: start docker services
    service:
      name: docker
      state: started

  - name: give 777 permissions on /var/run/docker.sock
    file:
      path: /var/run/docker.sock
      state: file
      mode: 0777

  - name: start docker on boot time
    service:
      name: docker
      enabled: yes 